controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

articulo_controller:
    path: /articulos
    controller: App\Controller\ArticuloController::index

un_articulo:
    path: /articulos/{slug}
    controller: App\Controller\ArticuloController::articulo_show